language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm rebuild node-sass
- npm run build
- npm run deploy
env:
  global:
    secure: hcfkOEEPT9PJp2tvw6IqBn8J8JMxoxPqe2JNDoQDHYZIC0+3ZqGN1EocZE1kMs67E0628zDUGzRBswv0moWFVeYTdaDZjIUkzovtbFD+G5dyWl/2Ja79ZXtJavTSAlruHoiFpVqnhDPA94qraHfbbdlURA3VSzrxPcziwGrIzWagjk43WYeLWIIY/MSh2bawOSAlFUt6twMV0Jg0k7fEcwEZNg+Kw2VTLrLU/z++YJB9wSvb0dFF7hThnA1prKVVLyL8Mt42K7GNoMsIYNVDFb4Ek0ios9GgBNkkK/MtD3hYhYEaVshSzuT1aAR7/RbU9/HoQ2iiHAK5xWYwgG4/8vP2/v7k3/Xtg0XWvGWHHE9BIBhToiOExDyjvKWf+dfd4WlmGmQ3UfvMV28AWzUVyl3v7o3sMjmwSgFeP3BfGvVmy7+edAUucacc6y1AaaZtBgWhbH/4WK5gw49hgLn3meZmVc0ZdPwbwt94yljwv6ZrDFkMWm75mRxJjbY8x6kuMpa6MFvOU66qmY4L4HEx1k0rMMwys0GT5wPXRfcIi66W6rWmU0iiw9LG6ttLNNdgpaxtcuCZ3+f2c5ety+iGXhPhFsVI0J5d+YTqQM7VFnXsrnFfenDgyjwNZCna5fyttMDYSJugEyxCXt1Wdxp2C64MoA7GZTCxn+smBfY2ye8=
notifications:
  slack:
    secure: OyuFuREpIndDbQQXBshwz63qCq/xfqgDZhehGlZBtt41J8hDXbHBWg8eoaDoRihpIbYM6U8lbDnZun7QJiuWXl/DKiuM9XxDK5CIpU9OWpjzJpljEQ3hpNU1H2aDovAnK5WGDCxuQ0d6yq0Etc9nbNm8bTqmKcJpLEX8PMfc7L0/whlbkbaASKbJ+7lrTR2eINLkzLlNh+VYsFLLEQVHWDzyGNMlvOUql9Lxh7OZ7OnHsmya0uDi/fHUEmPPwDzRzSuT7qraUyslhhAGmdtLJxPQIZcT+2h4VEY4sDc3Ei+HVBhtdrQKFfLb3w0b53txhvZ7nUjlk/tVueNjbsCjTDqPofJCNKTzN0wiN+yOrYnUPAvceOEn6Zlp4MuEIZzC7P8+gHwDsXrQ6MXGlPJagkJUq2AqdIZJYnEPeTafBKTM7CedG1FUkru+YwyeeMCHUMWPM91wj4rM5zFp8HBRxXgcGoTa9gk4cb3DFWpTajnthBsTFn1aVJTgUZrtFsZAXwFLdNodLWQrSyS8I5wEZa07aPKkhjbHoebTkXbzBmxv4zFfcnwgkXD2Q09sXW2qO2iMQ2qjphBB7Kk1+PQkGHt7Ui7wEP+nqHKTSs+Dff5FghZManF3wGNPJTu6vaSl2OuFIZuS8tGBL+KdkvBKuoZ6Ums4OJw4T636edXzlTQ=
    on_success: change
    on_failure: always
