language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run build
- "[[ -z $TRAVIS_TAG ]] || mvn clean deploy --settings settings.xml"
env:
  global:
  - secure: CuznrB4a/RYhyR7WkwL8CvA/j2WdIZLPuAhV5uaAwb12z2FOExZX9pWU7l5+NP8dVhVC27hXc9jZ6XVx2zzX6OlSwY66qcS7vOR5QLfB5uU8+4//DUvmMbLp/uNDHw55WFjXjPag0N+Hcj6fD6HYLCPv0Z1A/JMSCx5qoF2mZaX4xJH6csfWwTlL2hz7ohl9wy9VajQHU9oYuCP+ZrnUqVRbUEgMNYrOe94wz8477g7LISPqJMWFjiHb2b+9+jIPeHcZCHyQTSVNN8cOgzXTZPOwXCHnQgw2XomSeMZjNPSQMmt2kJv9Nad/OAmntVk15BeMtW7Ur31ZKKk+C4+8pRbAPFE5mZSiK9TyKpSCjd0SXXPqy4pmfGFnk+bIlkxXAFM/v6Zj27L4GfCos6g1ng1LiMW1JEFwiBjIWOgAUa5BG/ANfzib1nEEd4mo8YPCzHwjT6b8YXVAbxPZQRFijm6G42XeORZgjGgJ+swvRlht2Q4ekBAc1x1AgHd1zyWICZDPIueLr43BdzpI0GSeJWNF2pWMGBlzZIguTx0ekcsl7VDYhEYnNE9B3FSohTfpARFV3t/JRQgFqTxlBVjHKHqk5JV+B+FjfuxoH9MeQnpaihKGJl+lZo+YMI8CaxSpmZxtlKFe7vXB9cMXWz7NS6qdLllDvCNhUzveVZCfEnY=
  - secure: tg4qKaGB9xfzn0UZQ90/s/8FDG9tfz9sx6lI8cL/kl1fYYFxXwAWkSzkMDDgQpSWk1fFSFkxD1CxOOti4Zru5vjGqSK+y0pNHNji7yrOrKNAFPlja4d0kmKHQDOLLl3ehWnKkKBdgn7EsYsInMmxjLWaFE3GlLXEQPDLgoU7QKtioWIzKet6AOwt4jkxApwUj0X8MmIcG5nEk6xugTtpLOlt2Xgyzia9vutgTx8azs73AzB/tb/WnT/KTs0+0hXd3Lvmq0KLur957rsvVqZQ04KbrCjCx7JTRXBxJzFleNKsF9xJ5ORemGQBUWBYn9+XlI+SariY3qgZYOMFfGJc0srg0ia0dywgNLH4xv3naHed6vsol870+ijXVtJvWubS2jdCFx9Ug2Fhx4sD3iUKgEDIhhXffXbBUw8PddrXgWBD9tpIqOOtUO01rScCTx8VlMAk6ExRsTHRyOA0i93VOOhmOB3/yqlkGNYcjGB9Aw9IIvF5isLg3xFooQwrZNgi9djJrDAqF9sNY60KlW6YbU/ElU4sxkqu39IGBzgDz1xThxOHqaf/ng1s0uoiykbKKjdCS7/SIQ8lE8YpuYnc2fjcC5fl57KZ+/vl24MjybdQ2uTQfhVcalHUXdZddmz0hjdMmHhWm+JhlKYztSA2kpVwR9dFRuOYsxpGqAYK4Vk=
